# Project: Project2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Untitled3.o
LINKOBJ  = Untitled3.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib32" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -lglut32 -lglu32 -lopengl32 -lwinmm -lgdi32 glut/lib/GLAUX.LIB glut/lib/GLU32.LIB glut/lib/glut32.lib glut/lib/libgle.a glut/lib/libglsmap.a glut/lib/libglut32.a glut/lib/libmui.a glut/lib/OPENGL32.LIB -m32
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Oliver Swageritis/Desktop/UniGit/Informatik/4/Informatics 2/test files/glut/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"C:/Users/Oliver Swageritis/Desktop/UniGit/Informatik/4/Informatics 2/test files/glut/include"
BIN      = Project2.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32 -DGLUT_STATIC
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

Untitled3.o: Untitled3.c
	$(CC) -c Untitled3.c -o Untitled3.o $(CFLAGS)
